### ISSUE TITLE
Does Arrangement fitness function work properly?

### ISSUE THREAD

**Issue by thorstenmuellergithub** [informatik-mannheim/Moduro-CC3D#28]
In the class ArrangementFitnessSteppable within the overwritten step function. Does the arrangement fitness function work properly? If so how does it work?

- It uses a different function, then on the released paper (Proliferation and regeneration of the healthy human urothelium)

- By printing out the result of the function (with the simulation of SdPcdbCdiInDa) the result is very early almost by 1.0 (even there is only one intermediate layer and also when there was a stem cell in the intermediate layer) as you hopefully can see in the attached picture

```
    # step is overwritten
    # TODO sizes do not scale yet!
    def step(self, mcs):
        if self.execConfig.interuptMCS(mcs):
            deltaXPx = self.execConfig.calcPixelFromMuMeterMin1(20)  # 20 mu m.
            deltaZPx = deltaXPx
            sumFitness_a = []
            avgStemCellDiameterPx = \
                self.execConfig.calcPixelFromMuMeterMin1(self.model.cellTypes[2].getAvgDiameter())
            zRange = [0] if self.execConfig.zDimension == 1 else range(0, self.execConfig.zDimension, deltaZPx)
            for z in zRange:
                for x in xrange(1, self.execConfig.xDimension, deltaXPx):
                    cells_in_order = []
                    for y in xrange(3, self.execConfig.yDimension, int(avgStemCellDiameterPx / 2)):
                        # Gives the mode of a cell ID in a 3x3x3 pixels cube if 3D otherwise 3x3 rectangle
                        mode_of_cellIDs = []
                        for width in xrange(0, 2, 1):
                            for height in xrange(0, 2, 1):
                                depthRange = [0] if zRange.__len__() == 1 else range(0, 2, 1)
                                for depth in depthRange:
                                    if self.cellField[x + width, y + height, z + depth] is not None:
                                        mode_of_cellIDs.append(self.cellField[x + width, y + height, z + depth].id)
                        # If mode ID exists and in not already in cell_in_order list it will be added
                        if len(mode_of_cellIDs) > 0:
                            cellToCheck = self.attemptFetchingCellById(self.mode(mode_of_cellIDs))
                            exist = False
                            for cell in cells_in_order:
                                if cellToCheck.id == cell.id:
                                    exist = True
                            if not exist:
                                cells_in_order.append(cellToCheck)
                    layers = len(cells_in_order)
                    if layers == 0:
                        fitness_a = 0
                    else:
                        optimumLayers = 1 if layers <= 7 and layers >= 3 else 0
                        if cells_in_order[layers - 1].type == self.UMBRELLA:
                            lastLayer = 1
                            layers -= 1
                        else:
                            lastLayer = 0
                        if cells_in_order[0].type == self.STEM or cells_in_order[0].type == self.BASAL:
                            firstLayer = 1
                            layers -= 1
                        else:
                            firstLayer = 0
                        layersInBetween = layers
                        for x in range(firstLayer, len(cells_in_order) - 1 - lastLayer, 1):
                            if cells_in_order[x].type != self.INTERMEDIATE:
                                layersInBetween -= 1
                        lib = 0 if layers == 0 else (layers - layersInBetween) / layers
                        fitness_a = 1.0 - (
                            (1.0 - float(firstLayer)) +
                            (1.0 - float(lastLayer)) +
                            lib +
                            (1.0 - float(optimumLayers))) / 4.0
                    sumFitness_a.append(fitness_a)


            fitness_a = sum(sumFitness_a) / len(sumFitness_a)
            self._addLine(mcs, fitness_a)
            print "!!!!!!!!!!!!!!!!! x: ", x, " steps: ",  " fitness_a: ", fitness_a
```

![screenshot at 2017-12-06 13-23-10](https://user-images.githubusercontent.com/11176576/33661683-517ee3c2-da89-11e7-99d1-e3c7df24d58b.png)

**Comment by AngeloTorelli** [comment]
> Does the arrangement fitness function work properly?

Yes it does. The "new" Arrangement function does a better job though. The "new" version can be found [here](https://github.com/informatik-mannheim/Moduro-CC3D/blob/CellLineage/Simulation/Logger/ArrangementFitnessSteppable.py) which was implemented 2 years ago.

> If so how does it work?

As it is described in the code. firstLayer, lastLayer and optimumLayers are Boolean and are described a few previous lines of code above fitness_a. If they fulfill their requirement then they are equal to true / 1 otherwise false / 0. firstLayer looks for a basal or stem cell in the first layer. lastLayer looks for a umbrella cell in the last layer and optimumLayers only returns true / 1 if the number of all layers are between 3 and 7. lib in the other hand returns 0 if there is no layers in between the first and last otherwise it returns the layers in between minus the number of intermediate cells in between the first and last layer and normalizes it between 0 and 1 of course. fitness_a is calculated through the tissue in different locations as it was described [here]( https://link.springer.com/chapter/10.1007%2F978-3-319-16480-9_37). **For now on please do refer only to already published literature.**

> By printing out the result of the function (with the simulation of SdPcdbCdiInDa) the result is very early almost by 1.0 (even there is only one intermediate layer and also when there was a stem cell in the intermediate layer) as you hopefully can see in the attached picture

Yes. That is because everything is correct.
